#!/bin/sh
set -e

if [ "x$1" = xremove ] || [ "x$1" = xpurge ]; then
    if command -v update-desktop-database >/dev/null 2>&1; then
        update-desktop-database /usr/share/applications >/dev/null 2>&1 || true
    fi
fi
